# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('work_experience', models.FloatField()),
                ('analytics_experience', models.FloatField()),
                ('current_location', models.CharField(max_length=15)),
                ('corrected_location', models.CharField(max_length=15)),
                ('nearest_city', models.CharField(max_length=15)),
                ('prefered_location', models.CharField(max_length=15)),
                ('ctc', models.FloatField()),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Skill'),
        ),
    ]
